package testPrograma;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import funcionesYObjetos.*;

public class ProductoTest {
	@Test
	public void testProductos() {
		String nombreProductoTest = "Lacasitos";
		int codigoProductoTest = 3;
		float precioProductoTest = 22f;
		float precioIvaTest = (Math.round((precioProductoTest * (1f + 0.21f)) * 100f)) / 100f;
		int cantidadTest = 0;
		Producto productoTest = new Producto(nombreProductoTest, codigoProductoTest, precioProductoTest);

		assertEquals(productoTest.nombre, nombreProductoTest);
		assertEquals(productoTest.codigo, codigoProductoTest);
		assertEquals(productoTest.precio, precioProductoTest, 0);
		assertEquals(productoTest.precioIva, precioIvaTest, 0);
		assertEquals(productoTest.cantidad, cantidadTest);
	}
}
